In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [14]:
iris = load_iris()

In [21]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target,cv=3, n_jobs=3)
l_scores

array([0.98, 0.96, 0.98])

In [22]:
np.average(lr_score)

0.9733333333333334

In [29]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
d_scores

array([0.98, 0.92, 1.  ])

In [30]:
np.average(d_scores)

0.9666666666666667

In [27]:
s_scores = cross_val_score(SVC(), iris.data, iris.target, cv=3)
s_scores

array([0.96, 0.98, 0.94])

In [28]:
np.average(s_scores)

0.96